backend:
  name: github
  repo: matthewjoelbrooks/webdes
  branch: main
  auth_type: github_app
  app_id: Ov23liJR9KgEy2RUsJpk

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Categories", name: "categories", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    folder: ""
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
    filter:
      field: "layout"
      value: "default"
